export const DEFAULT_SCORE_PER_TAP = 1;
export const DEFAULT_ENERGY_PER_TAP = 1;
export const DEFAULT_RESTORE_ENERGY_PER_SECOND = 3;
export const DEFAULT_BASE_ENERGY = 1000;
export const DEFAULT_BASE_SCORE = 25000;

