
import {getBase64} from "../hooks/useBase64";

import {inventoryIcon, inventoryImage} from "../elements/Inventory/Inventory";

export const inventoryIcons =  {
  inventory_base_outerwear_0_0: getBase64(inventoryIcon('inventory_base_outerwear_0_0')),
  inventory_base_pants_0_0: getBase64(inventoryIcon('inventory_base_pants_0_0')),
  inventory_base_shoes_0_0: getBase64(inventoryIcon('inventory_base_shoes_0_0')),
  inventory_base_weapon_0_0: getBase64(inventoryIcon('inventory_base_weapon_0_0')),
  inventory_common_headdress_1_1: getBase64(inventoryIcon('inventory_common_headdress_1_1')),
  inventory_common_outerwear_1_1: getBase64(inventoryIcon('inventory_common_outerwear_1_1')),
  inventory_common_pants_1_1: getBase64(inventoryIcon('inventory_common_pants_1_1')),
  inventory_common_shoes_1_1: getBase64(inventoryIcon('inventory_common_shoes_1_1')),
  inventory_common_weapon_1_1: getBase64(inventoryIcon('inventory_common_weapon_1_1')),
  inventory_common_headdress_2_1: getBase64(inventoryIcon('inventory_common_headdress_2_1')),
  inventory_common_outerwear_2_1: getBase64(inventoryIcon('inventory_common_outerwear_2_1')),
  inventory_common_pants_2_1: getBase64(inventoryIcon('inventory_common_pants_2_1')),
  inventory_common_shoes_2_1: getBase64(inventoryIcon('inventory_common_shoes_2_1')),
  inventory_common_weapon_2_1: getBase64(inventoryIcon('inventory_common_weapon_2_1')),
  inventory_common_headdress_3_1: getBase64(inventoryIcon('inventory_common_headdress_3_1')),
  inventory_common_outerwear_3_1: getBase64(inventoryIcon('inventory_common_outerwear_3_1')),
  inventory_common_pants_3_1: getBase64(inventoryIcon('inventory_common_pants_3_1')),
  inventory_common_shoes_3_1: getBase64(inventoryIcon('inventory_common_shoes_3_1')),
  inventory_common_weapon_3_1: getBase64(inventoryIcon('inventory_common_weapon_3_1')),
  inventory_uncommon_headdress_1_1: getBase64(inventoryIcon('inventory_uncommon_headdress_1_1')),
  inventory_uncommon_outerwear_1_1: getBase64(inventoryIcon('inventory_uncommon_outerwear_1_1')),
  inventory_uncommon_pants_1_1: getBase64(inventoryIcon('inventory_uncommon_pants_1_1')),
  inventory_uncommon_shoes_1_1: getBase64(inventoryIcon('inventory_uncommon_shoes_1_1')),
  inventory_uncommon_weapon_1_1: getBase64(inventoryIcon('inventory_uncommon_weapon_1_1')),
  inventory_uncommon_headdress_2_1: getBase64(inventoryIcon('inventory_uncommon_headdress_2_1')),
  inventory_uncommon_outerwear_2_1: getBase64(inventoryIcon('inventory_uncommon_outerwear_2_1')),
  inventory_uncommon_pants_2_1: getBase64(inventoryIcon('inventory_uncommon_pants_2_1')),
  inventory_uncommon_shoes_2_1: getBase64(inventoryIcon('inventory_uncommon_shoes_2_1')),
  inventory_uncommon_weapon_2_1: getBase64(inventoryIcon('inventory_uncommon_weapon_2_1')),
  inventory_uncommon_headdress_3_1: getBase64(inventoryIcon('inventory_uncommon_headdress_3_1')),
  inventory_uncommon_outerwear_3_1: getBase64(inventoryIcon('inventory_uncommon_outerwear_3_1')),
  inventory_uncommon_pants_3_1: getBase64(inventoryIcon('inventory_uncommon_pants_3_1')),
  inventory_uncommon_shoes_3_1: getBase64(inventoryIcon('inventory_uncommon_shoes_3_1')),
  inventory_uncommon_weapon_3_1: getBase64(inventoryIcon('inventory_uncommon_weapon_3_1')),
  inventory_rare_headdress_1_1: getBase64(inventoryIcon('inventory_rare_headdress_1_1')),
  inventory_rare_outerwear_1_1: getBase64(inventoryIcon('inventory_rare_outerwear_1_1')),
  inventory_rare_pants_1_1: getBase64(inventoryIcon('inventory_rare_pants_1_1')),
  inventory_rare_shoes_1_1: getBase64(inventoryIcon('inventory_rare_shoes_1_1')),
  inventory_rare_weapon_1_1: getBase64(inventoryIcon('inventory_rare_weapon_1_1')),
  inventory_rare_headdress_2_1: getBase64(inventoryIcon('inventory_rare_headdress_2_1')),
  inventory_rare_outerwear_2_1: getBase64(inventoryIcon('inventory_rare_outerwear_2_1')),
  inventory_rare_pants_2_1: getBase64(inventoryIcon('inventory_rare_pants_2_1')),
  inventory_rare_shoes_2_1: getBase64(inventoryIcon('inventory_rare_shoes_2_1')),
  inventory_rare_weapon_2_1: getBase64(inventoryIcon('inventory_rare_weapon_2_1')),
  inventory_rare_headdress_3_1: getBase64(inventoryIcon('inventory_rare_headdress_3_1')),
  inventory_rare_outerwear_3_1: getBase64(inventoryIcon('inventory_rare_outerwear_3_1')),
  inventory_rare_pants_3_1: getBase64(inventoryIcon('inventory_rare_pants_3_1')),
  inventory_rare_shoes_3_1: getBase64(inventoryIcon('inventory_rare_shoes_3_1')),
  inventory_rare_weapon_3_1: getBase64(inventoryIcon('inventory_rare_weapon_3_1')),
  inventory_epic_headdress_1_1: getBase64(inventoryIcon('inventory_epic_headdress_1_1')),
  inventory_epic_outerwear_1_1: getBase64(inventoryIcon('inventory_epic_outerwear_1_1')),
  inventory_epic_pants_1_1: getBase64(inventoryIcon('inventory_epic_pants_1_1')),
  inventory_epic_shoes_1_1: getBase64(inventoryIcon('inventory_epic_shoes_1_1')),
  inventory_epic_weapon_1_1: getBase64(inventoryIcon('inventory_epic_weapon_1_1')),
  inventory_epic_headdress_2_1: getBase64(inventoryIcon('inventory_epic_headdress_2_1')),
  inventory_epic_outerwear_2_1: getBase64(inventoryIcon('inventory_epic_outerwear_2_1')),
  inventory_epic_pants_2_1: getBase64(inventoryIcon('inventory_epic_pants_2_1')),
  inventory_epic_shoes_2_1: getBase64(inventoryIcon('inventory_epic_shoes_2_1')),
  inventory_epic_weapon_2_1: getBase64(inventoryIcon('inventory_epic_weapon_2_1')),
  inventory_epic_headdress_3_1: getBase64(inventoryIcon('inventory_epic_headdress_3_1')),
  inventory_epic_outerwear_3_1: getBase64(inventoryIcon('inventory_epic_outerwear_3_1')),
  inventory_epic_pants_3_1: getBase64(inventoryIcon('inventory_epic_pants_3_1')),
  inventory_epic_shoes_3_1: getBase64(inventoryIcon('inventory_epic_shoes_3_1')),
  inventory_epic_weapon_3_1: getBase64(inventoryIcon('inventory_epic_weapon_3_1')),
  inventory_legendary_headdress_1_1: getBase64(inventoryIcon('inventory_legendary_headdress_1_1')),
  inventory_legendary_outerwear_1_1: getBase64(inventoryIcon('inventory_legendary_outerwear_1_1')),
  inventory_legendary_pants_1_1: getBase64(inventoryIcon('inventory_legendary_pants_1_1')),
  inventory_legendary_shoes_1_1: getBase64(inventoryIcon('inventory_legendary_shoes_1_1')),
  inventory_legendary_weapon_1_1: getBase64(inventoryIcon('inventory_legendary_weapon_1_1')),
  inventory_legendary_headdress_2_1: getBase64(inventoryIcon('inventory_legendary_headdress_2_1')),
  inventory_legendary_outerwear_2_1: getBase64(inventoryIcon('inventory_legendary_outerwear_2_1')),
  inventory_legendary_pants_2_1: getBase64(inventoryIcon('inventory_legendary_pants_2_1')),
  inventory_legendary_shoes_2_1: getBase64(inventoryIcon('inventory_legendary_shoes_2_1')),
  inventory_legendary_weapon_2_1: getBase64(inventoryIcon('inventory_legendary_weapon_2_1')),
};

export const inventoryImages =  {
  inventory_base_headdress_0_0: getBase64(inventoryImage('inventory_base_headdresse_0_0')),
  inventory_base_outerwear_0_0: getBase64(inventoryImage('inventory_base_outerwear_0_0')),
  inventory_base_pants_0_0: getBase64(inventoryImage('inventory_base_pants_0_0')),
  inventory_base_shoes_0_0: getBase64(inventoryImage('inventory_base_shoes_0_0')),
  inventory_base_weapon_0_0: getBase64(inventoryImage('inventory_base_weapon_0_0')),
};
